services:
  postgres:
    # Lightweight image
    image: postgres:18.3-alpine
    container_name: iis2_dwh_postgres
    environment:
      POSTGRES_USER: iis2
      POSTGRES_PASSWORD: iis2
      POSTGRES_DB: nordwind
    ports:
      - "5433:5432"
    volumes:
      # Persist data between restarts
      - pgdata:/var/lib/postgresql
      # Initialize the database with SQL scripts
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  # Volume for PostgreSQL data persistence
  pgdata: